### PR TITLE
Adding Kris' Work - New Add Item Functionality 

### PR DESCRIPTION
**Pull request by KrisCovert**
Adding new "Add Item" functionality to the app. New features include the list of items and a "+" button that activates the Add Item window to pop up, allowing the user to add items to the list.

### CODE REVIEW

**Comment by KrisCovert** [comment]
Can you guys check out my code before I merge? Only conflicting file is the README. Check out the contents of the README and let me know what you think!

**Comment by lustyun** [comment]
looks good to me to merge kris! this will be our base files right?

**Review by lustyun — APPROVED** [review]

**Review by JacobSchnur — APPROVED** [review]
After looking at the code it looks good to me. Definitely a good starting point for the project. Good job Kris.

**Comment by KrisCovert** [comment]
> looks good to me to merge kris! this will be our base files right?

Yes these will be the base of our project so far!

**Pull request merged**
