### PR TITLE
Adrian

### PR DESCRIPTION
**Pull request by Adrian-Tarnowski**
Adding HomeScreen.js and CustomButton.js to main so that our main has home screen!

### CODE REVIEW

**Review by KrisCovert — COMMENTED** [review]
All looks good. I do have one thing to point out though. HomeScreen.js line 6 is exporting the component as “App.” This might be confusing since this is HomeScreen.js not App.js

**Comment by lustyun** [comment]
> All looks good. I do have one thing to point out though. HomeScreen.js line 6 is exporting the component as “App.” This might be confusing since this is HomeScreen.js not App.js

I think he did it just to be able to merge without replacing main app.js. so theres two copy of it

**Comment by Adrian-Tarnowski** [comment]
Thanks for pointing that out. I just tried to run it and yeah renaming it was a bad idea. I'll rename it back to app.js and merge it with main app.js and just comment out the original app.js work. I think that should be fine. Let me know if that work for y'all.

**Comment by KrisCovert** [comment]
Conflicts are done!

**Review by KrisCovert — APPROVED** [review]
Looks good to me.

**Comment by Adrian-Tarnowski** [comment]
Thank you.

**Pull request merged**
