### PR TITLE
Jacob final branch

### PR DESCRIPTION
**Pull request by JacobSchnur**
This is the my final pull request. It's been a fun time guys. Thanks for the great semester.

### CODE REVIEW

**Comment by justincrawford-wsu** [comment]
The final addition. Love it. Great job everyone!

**Comment by KrisCovert** [comment]
Jacob, thank you for adding the the splash screen, our final functionality to our project. It looks great!

**Comment by lustyun** [comment]
Great work Jacob on getting the splash screen done! Topping our project off with a final touch!

**Comment by Adrian-Tarnowski** [comment]
Code looks good. Good job on adding the splashscreen! The splashscreen lives on!

**Pull request merged**
